<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Г.Махгал">

<title>Унадаг дугуйчдын амжилт ба насны хамаарал</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Bicycle Race_files/libs/clipboard/clipboard.min.js"></script>
<script src="Bicycle Race_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Bicycle Race_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Bicycle Race_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Bicycle Race_files/libs/quarto-html/popper.min.js"></script>
<script src="Bicycle Race_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Bicycle Race_files/libs/quarto-html/anchor.min.js"></script>
<link href="Bicycle Race_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Bicycle Race_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Bicycle Race_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Bicycle Race_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Bicycle Race_files/libs/bootstrap/bootstrap-30b9709962c6823664ef69f9507cd0c7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Агуулга</h2>
   
  <ul>
  <li><a href="#өгөгдөл" id="toc-өгөгдөл" class="nav-link active" data-scroll-target="#өгөгдөл"><span class="header-section-number">1</span> Өгөгдөл</a>
  <ul class="collapse">
  <li><a href="#өгөгдөл-ачаалах" id="toc-өгөгдөл-ачаалах" class="nav-link" data-scroll-target="#өгөгдөл-ачаалах"><span class="header-section-number">1.1</span> Өгөгдөл ачаалах</a></li>
  <li><a href="#өгөгдлийг-шинжилгээнд-бэлдэх" id="toc-өгөгдлийг-шинжилгээнд-бэлдэх" class="nav-link" data-scroll-target="#өгөгдлийг-шинжилгээнд-бэлдэх"><span class="header-section-number">1.2</span> Өгөгдлийг шинжилгээнд бэлдэх</a></li>
  </ul></li>
  <li><a href="#тамирчдын-амжилт-ба-нас-хоорондын-хамаарал" id="toc-тамирчдын-амжилт-ба-нас-хоорондын-хамаарал" class="nav-link" data-scroll-target="#тамирчдын-амжилт-ба-нас-хоорондын-хамаарал"><span class="header-section-number">2</span> Тамирчдын амжилт ба нас хоорондын хамаарал</a>
  <ul class="collapse">
  <li><a href="#регрессийн-шинжилгээ" id="toc-регрессийн-шинжилгээ" class="nav-link" data-scroll-target="#регрессийн-шинжилгээ"><span class="header-section-number">2.1</span> Регрессийн шинжилгээ</a></li>
  <li><a href="#хоёр-дахь-шатны-регрессийн-шинжилгээ" id="toc-хоёр-дахь-шатны-регрессийн-шинжилгээ" class="nav-link" data-scroll-target="#хоёр-дахь-шатны-регрессийн-шинжилгээ"><span class="header-section-number">2.2</span> Хоёр дахь шатны регрессийн шинжилгээ</a></li>
  <li><a href="#дисперсийн-шинжилгээ" id="toc-дисперсийн-шинжилгээ" class="nav-link" data-scroll-target="#дисперсийн-шинжилгээ"><span class="header-section-number">2.3</span> Дисперсийн шинжилгээ</a></li>
  </ul></li>
  <li><a href="#нэмэлт-шинжилгээ" id="toc-нэмэлт-шинжилгээ" class="nav-link" data-scroll-target="#нэмэлт-шинжилгээ"><span class="header-section-number">3</span> Нэмэлт шинжилгээ</a>
  <ul class="collapse">
  <li><a href="#унадаг-дугуйчдын-жийлтийн-эрчим-хэвийн-тархалттай-эсэх" id="toc-унадаг-дугуйчдын-жийлтийн-эрчим-хэвийн-тархалттай-эсэх" class="nav-link" data-scroll-target="#унадаг-дугуйчдын-жийлтийн-эрчим-хэвийн-тархалттай-эсэх"><span class="header-section-number">3.1</span> Унадаг дугуйчдын жийлтийн эрчим хэвийн тархалттай эсэх</a></li>
  <li><a href="#жийлтийн-эрчмийн-вариацын-цувааны-минимал-ба-максимал-элементүүдийн-корреляц" id="toc-жийлтийн-эрчмийн-вариацын-цувааны-минимал-ба-максимал-элементүүдийн-корреляц" class="nav-link" data-scroll-target="#жийлтийн-эрчмийн-вариацын-цувааны-минимал-ба-максимал-элементүүдийн-корреляц"><span class="header-section-number">3.2</span> Жийлтийн эрчмийн вариацын цувааны минимал ба максимал элементүүдийн корреляц</a></li>
  </ul></li>
  <li><a href="#дүгнэлт" id="toc-дүгнэлт" class="nav-link" data-scroll-target="#дүгнэлт">Дүгнэлт</a></li>
  <li><a href="#ашигласан-материал" id="toc-ашигласан-материал" class="nav-link" data-scroll-target="#ашигласан-материал">Ашигласан материал</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Унадаг дугуйчдын амжилт ба насны хамаарал</h1>
<p class="subtitle lead">Морь хурдан уу, дугуй хурдан уу тэмцээний дүн дээрх өгөгдлийн шинжилгээ</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Зохиогч</div>
    <div class="quarto-title-meta-contents">
             <p>Г.Махгал </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Нийтлэгдсэн</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026 оны 3-р сарын 3</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="өгөгдөл" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Өгөгдөл</h1>
<p>Унадаг дугуйчдын амжилт наснаас хамаардаг уу гэсэн асуултад хариулахын тулд 2024 оны 5 сарын 18 өдөр Монголын дугуйн холбоо, Монгол наадам цогцолбор болон Номадик дугуйн клуб хамтран зохиосон&nbsp;Морь хурдан уу дугуй хурдан уу тэмцээнийн дүнг авч үзье. Өөрөөр хэлбэл тус асуултад өгөгдлийн шинжилгээгээр хариулна. Өгөгдлийг Монголын дугуйн холбооны хуучин Фейсбүүк пейж <span class="citation" data-cites="mcf_facebook"><a href="#ref-mcf_facebook" role="doc-biblioref">[1]</a></span> дээрх мэдээ дэх зургуудаас хиймэл оюуны OCR багажийн тусламжтай гарган авсан.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">c</span>(<span class="st">"data/1.jpg"</span>, <span class="st">"data/2.jpg"</span>, <span class="st">"data/3.jpg"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="fig-data-source" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-source-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-data-source" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-data-source-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-data-source-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/1.jpg" class="img-fluid figure-img" data-ref-parent="fig-data-source">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-data-source-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) 17-29 болон 30-39 нас
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-data-source" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-data-source-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-data-source-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/2.jpg" class="img-fluid figure-img" data-ref-parent="fig-data-source">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-data-source-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) 30-39 болон 40-49 нас
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-data-source" style="flex-basis: 33.3%;justify-content: flex-start;">
<div id="fig-data-source-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-data-source-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="data/3.jpg" class="img-fluid figure-img" data-ref-parent="fig-data-source">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-data-source-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) 40-49 нас
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-source-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;1: Монголын дугуйн холбооны хуучин Фейсбүүк пейж дээр нийтэлсэн тэмцээний дүн
</figcaption>
</figure>
</div>
<p>Ийнхүү бэлдсэн өгөгдлийг CSV форматтай файл болгоод <a href="https://www.magadlal.com/">www.magadlal.com</a> веб сайт <span class="citation" data-cites="magadlal_web"><a href="#ref-magadlal_web" role="doc-biblioref">[2]</a></span> дээр хадгалсан. Өгөгдлийн шинжилгээг R програмын 4.5.2 хувилбар <span class="citation" data-cites="R"><a href="#ref-R" role="doc-biblioref">[3]</a></span> дээр хийв.</p>
<section id="өгөгдөл-ачаалах" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="өгөгдөл-ачаалах"><span class="header-section-number">1.1</span> Өгөгдөл ачаалах</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="st">"https://www.magadlal.com/d/datasets/race.csv"</span> <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read.csv</span>(<span class="at">skip =</span> <span class="dv">1</span>) <span class="ot">-&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  race</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Ачаалсан өгөгдлийн 5 мөрийг санамсаргүй сонгоод хэвлэж харуулав.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">0</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>race[<span class="fu">sort</span>(<span class="fu">sample.int</span>(<span class="at">n =</span> <span class="fu">nrow</span>(race), <span class="at">size =</span> <span class="dv">5</span>)),] <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Байр    Овог.нэр Нас Харьяа.байгууллага...Клуб Хувийн.дугаар   Амжилт
1     1   Б.Батбаяр  20             Мөнгөн Хэгээс           239 00:52:11
14   14   Ч.Анхбаяр  21         Darkhan road team           217 01:03:12
34   12    У.Одбаяр  38                       УДА           311 01:00:32
39   17 Д.Гэрэлт-Од  38                  Хувиараа           319 01:04:18
68    3    Г.Махгал  42                       УДА           408 00:56:57</code></pre>
</div>
</div>
</section>
<section id="өгөгдлийг-шинжилгээнд-бэлдэх" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="өгөгдлийг-шинжилгээнд-бэлдэх"><span class="header-section-number">1.2</span> Өгөгдлийг шинжилгээнд бэлдэх</h2>
<p>Хувьсагчдыг дуудах баганын нэрс зохимжгүй байгаа тул багануудын нэрийг солив.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(race) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"place"</span>, <span class="st">"name"</span>, <span class="st">"age"</span>, <span class="st">"club"</span>, <span class="st">"number"</span>, <span class="st">"time"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Түүнчлэн тамирчдын амжилтыг илэрхийлэх хувьсагчийн утга 00:52:11 буюу HH:MM:SS форматтай character төрлийнх байгааг time төрөл рүү хувиргана. Улмаар тус хувьсагчийн утгуудыг хамгийн түрүүнд тэмцээний барианд орсон тамирчнаас тухайн тамирчин хэдэн секундын дараа барианд орсоныг секундээр илэрхийлдэг болгов. Тус шинэ хувьсагчийг <code>seconds</code> гэж нэрлэсэн.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>race<span class="sc">$</span>seconds <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">difftime</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.POSIXct</span>(race<span class="sc">$</span>time, <span class="at">format =</span> <span class="st">"%H:%M:%S"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.POSIXct</span>(<span class="st">"00:00:00"</span>, <span class="at">format =</span> <span class="st">"%H:%M:%S"</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">units =</span> <span class="st">"secs"</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="тамирчдын-амжилт-ба-нас-хоорондын-хамаарал" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Тамирчдын амжилт ба нас хоорондын хамаарал</h1>
<p>Тэмцээний дүн мэдээнээс зөвхөн эрэгтэйчүүдийн сонирхогч ангиллын тамирчдын 17-29, 30-39 болон 40-49 насыг л авсан. Өөрөөр хэлбэл seconds хувьсагч нь хүйс ба мэргэжлийн тамирчид зэрэг хүчин зүйлийн нөлөөнөөс ангид юм. Өөрөөр хэлбэл тус хувьсагч дээр зөвхөн насны нөлөө л байж болно.</p>
<p><code>seconds</code> болон <code>age</code> хувьсагчдын хамаарлыг цэгэн диаграммаар дүрслэн харуулав.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> race<span class="sc">$</span>age, <span class="at">y =</span> race<span class="sc">$</span>seconds, <span class="at">xlab =</span> <span class="st">"Age"</span>, <span class="at">ylab =</span> <span class="st">"Time"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-scatterplot-secnods-age" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatterplot-secnods-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-scatterplot-secnods-age-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatterplot-secnods-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;2: Тамирчдын амжилт ба нас хоорондын хамаарал
</figcaption>
</figure>
</div>
</div>
</div>
<p>Хоёр хувьсагчийн хамаарлыг шугаман хэлбэртэй гэмээр тул хамаарлыг статистикийн шугаман загвараар илэрхийлэгдэнэ гэж таамаглана. Өөрөөр хэлбэл шугаман регрессийн шинжилгээ хийнэ.</p>
<section id="регрессийн-шинжилгээ" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="регрессийн-шинжилгээ"><span class="header-section-number">2.1</span> Регрессийн шинжилгээ</h2>
<p>Одоо дээр дурдсанчлан шугаман регрессийн шинжилгээ <span class="citation" data-cites="james2021introduction"><a href="#ref-james2021introduction" role="doc-biblioref">[4]</a></span> хийнэ. Ингээд <code>seconds</code> болон <code>age</code> хувьсагчдын хамаарлыг <span class="math display">\[\text{seconds}=a+b\cdot\text{age}\]</span> шугаман загвараар илэрхийлэгдэнэ гэж таамаглана.</p>
<p>Эхлээд загварын парамтрүүдийг үнэлнэ.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> seconds <span class="sc">~</span> age, <span class="at">data =</span> race)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Шугаман загварын хувьд үлдэгдлийн дисперс тогтмол, үлдэгдэл хэвийн тархалттай зэрэг таамаглал биелнэ гэж тооцдог. Эдгээр таамаглал хэр үнэмшилтэй байгааг харахаар загварын оношлогооны диаграммуудыг байгуулна. Бас таамаглалуудыг зохих шинжүүрээр шалгана.</p>
<p>Таамаглалуудыг 0.05 ач холбогдлын түвшинд шалгана.</p>
<p>Сая шугаман загварыг ашиглах үед тодорхой таамаглалуудыг биелнэ гэсэн шаардлага тавьдаг гэсэн. Мөн түүнчлэн өөр нэг шаардлага тавьдаг. Энэ бол түүврийн элементүүд хамааралгүй гэдэг шаардлага юм. Хэрэв хамааралтай бол өгөгдлийг өөр загвараар шинжилдэг. Манай тохиолдолд түүврийн элементүүд нь тэмцээнд оролцогч тамирчид юм. Тамирчдын амжилт буюу жийлтийн эрчим нь өөр хоорондоо хамааралгүй гэсэн таамаглал биелнэ гэж үзэх үндэстэй. Учир нь Морь хурдан уу, дугуй хурдан уу уралдааны үеэр тамирчид “толгой толгойгоо даан” жийцгээдэг. Өөрөөр хэлбэл баг багаараа хамтарч салхиа авах гэх мэтчилэн арга хэрэглэдэггүй. Миний ажиглалтаар ийм арга хэрэглэхээр оролдсон нь замын бартаанд онхолдох зэргээр бүтэлгүйтдэг юм билээ. Иймдээ ч тамирчид тус тэмцээнд оролцохдоо тийнхүү толгой толгойгоо даан хамааралгүйгээр уралддаг биз ээ. Дүгнэвээс, түүврийн элементүүд хамааралгүй буюу шугаман загвар дээрх уг шаардлага биелнэ хэмээн үзнэ.</p>
<p>Эхлээд үлдэгдлийн дисперс тогтмол гэсэн таамаглалыг авч үзье. Residuals vs Fitted диаграмм байгуулж харвал ерөнхийдөө хонгил хэлбэр л ажиглагдана. Диаграммыг дараах тушаалаар байгуулна.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-lm-diagnoses-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lm-diagnoses-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-lm-diagnoses-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lm-diagnoses-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;3: Шугаман загварын оношлогооны Residuals vs Fitted диаграмм
</figcaption>
</figure>
</div>
</div>
</div>
<p>Бас Scale-Location диаграмм ашиглаж болно.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit, <span class="at">which =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-lm-diagnoses-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lm-diagnoses-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-lm-diagnoses-3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lm-diagnoses-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;4: Шугаман загварын оношлогооны Scale-Location диаграмм
</figcaption>
</figure>
</div>
</div>
</div>
<p>Диаграмм харж “нүдээрээ” дүгнэлт гаргах нь өрөөсгөл юм. Иймээс үлдэгдлийн дисперс тогтмол эсэхийг Бройш-Паганы шинжүүрээр <span class="citation" data-cites="breusch1979simple"><a href="#ref-breusch1979simple" role="doc-biblioref">[5]</a></span> шалгана. Шинжүүрийг хэрэглэхдээ lmtest багц <span class="citation" data-cites="zeileis2002diagnostic"><a href="#ref-zeileis2002diagnostic" role="doc-biblioref">[6]</a></span> ашиглав.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">bptest</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  fit
BP = 0.069525, df = 1, p-value = 0.792</code></pre>
</div>
</div>
<p>Дээрх үр дүн нь тус шинжүүр тэг таамаглалыг 0.05 ач холбогдлын түвшинд үл няцааж буйг илтгэнэ.</p>
<p>Одоо шугаман загварын үлдэгдэл хэвийн тархалттай гэдэг таамаглалыг шалгана. Тархалт хэвийн эсэхийг Q-Q диаграммаас ажиглаж болно.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit, <span class="at">which =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-lm-diagnoses-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lm-diagnoses-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-lm-diagnoses-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lm-diagnoses-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;5: Шугаман загварын оношлогооны Q-Q диаграмм
</figcaption>
</figure>
</div>
</div>
</div>
<p>Диаграммыг харвал хэвийн тархалттай гэмээргүй төрх ажиглагдана. Гэсэн хэдий ч уг таамаглалыг зохих шинжүүрээр нь шалгана. Ингээд загварын үлдэгдлийг олж улмаар үлдэгдэл хэвийн тархалттай гэсэн тэг таамаглалыг Шафиро-Уилкийн шинжүүрээр <span class="citation" data-cites="shapiro1965analysis"><a href="#ref-shapiro1965analysis" role="doc-biblioref">[7]</a></span> шалгана.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fit <span class="sc">|&gt;</span> <span class="fu">residuals</span>() <span class="sc">|&gt;</span> <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(fit)
W = 0.83388, p-value = 6.923e-09</code></pre>
</div>
</div>
<p><span class="math inline">\(p\text{-утга}=6.9228853\times 10^{-9}&lt;0.05\)</span> гэж гарсан нь бидний авч үзэж буй шугаман загварын үлдэгдэл хэвийн тархалттай гэсэн тэг таамаглалыг тус шинжүүр 0.05 ач холбогдлын түвшинд няцааж буйг илтгэнэ. Энэ бол нэг талаас өгөгдөл дотор, шугаман загвартай харшлах онцгой утгууд байна гэсэн үг юм. Мөн нөгөө талаас шугаман бус хамааралтай хувьсагчид дээр шугаман загвар хэрэглэсэн байж болно. Гэхдээ дээрх оношлогооны диаграммуудыг ажиглавал өгөгдлийг агуулж буй датафреймын 64, 65 болон 94 гэсэн дугаартай мөрүүд дэх утгууд хэт хазайлттай үлдэгдэл ба хэвийн тархалтаас гажих явдлыг нөхцөлдүүлж буй нь харагдана. Харин шугаман бус хамаарал бий гэдэг нь саяын дүгнэлтээс үнэмшил муутай. Иймээс тэдгээр гурван утгыг өгөгдлөөс зайлуулна.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>race <span class="ot">&lt;-</span> race[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">64</span>, <span class="dv">65</span>, <span class="dv">94</span>),]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Ийнхүү өгөгдөлд цэвэрлэгээ хийсэн тул шугаман загварыг ахин ажиллуулна. Түүнчлэн шугаман бус хамаарал гэдэг хүчин зүйлийг ч орхиж болохгүй. Иймээс 64, 65 болон 94 дугаартай мөрүүдийг зайлуулсан өгөгдөл дээр загвараа ахин үнэлээд улмаар Бокс-Коксын хувиргалт <span class="citation" data-cites="boxcox1964"><a href="#ref-boxcox1964" role="doc-biblioref">[8]</a></span> хийнэ. Тус хувиргалт нь үлдэгдлийг хэвийн тархалттай болгоход ач холбогдолтой. Эцэст нь ингэж хувиргасны дараах өгөгдөл дээр шугаман загварыг ахин ажиллуулаад, гарсан үр дүнг нь нарийвчлан шинжилнэ.</p>
</section>
<section id="хоёр-дахь-шатны-регрессийн-шинжилгээ" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="хоёр-дахь-шатны-регрессийн-шинжилгээ"><span class="header-section-number">2.2</span> Хоёр дахь шатны регрессийн шинжилгээ</h2>
<p>Энэ удаад цэвэрлэсэн өгөгдөл дээр регрессийн шинжилгээ хийнэ.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> seconds <span class="sc">~</span> age, <span class="at">data =</span> race)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Үлдэгдлийн тархалтыг хэвийн болгох зорилгоор Бокс-Коксын хувиргалт хийнэ. Мөн энэ нь үлдэгдлийн дисперсийн тогтмол бус байдлыг засахад ч ач холбогдолтой. Хувиргалтыг MASS багц <span class="citation" data-cites="venables2002modern"><a href="#ref-venables2002modern" role="doc-biblioref">[9]</a></span> ашиглан гүйцэтгэв.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>bc <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">boxcox</span>(fit, <span class="at">plotit =</span> <span class="cn">FALSE</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> bc<span class="sc">$</span>x[<span class="fu">which.max</span>(bc<span class="sc">$</span>y)]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>bc_transform <span class="ot">&lt;-</span> \(y, lambda) {</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">abs</span>(lambda) <span class="sc">&lt;</span> <span class="fl">1e-6</span>) {</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">log</span>(y)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    (y<span class="sc">^</span>lambda <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> lambda</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>race<span class="sc">$</span>seconds_bc <span class="ot">&lt;-</span> <span class="fu">bc_transform</span>(race<span class="sc">$</span>seconds, lambda)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Хувиргалтаар үүссэн шинэ хувьсагчийг <code>seconds_bc</code> гэж нэрлэв.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> seconds_bc <span class="sc">~</span> age, <span class="at">data =</span> race)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Одоо нэн тэргүүнд өмнө зөрчигдөж байсан шаардлага буюу загварын үлдэгдэл хэвийн тархалттай гэсэн таамаглалыг шалгана.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fit <span class="sc">|&gt;</span> <span class="fu">residuals</span>() <span class="sc">|&gt;</span> <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(fit)
W = 0.97886, p-value = 0.1454</code></pre>
</div>
</div>
<p><span class="math inline">\(p\text{-утга}\)</span> 0.05 ач холбогдлын түвшингээс их гарсан буюу үлдэгдэл хэвийн тархалттай гэсэн тэг таамаглалыг үл няцаана. Түүнчлэн үлдэгдлийн дисперс тогтмол гэсэн тэг таамаглалыг шалгахад <span class="math inline">\(p\text{-утга}=0.2494367\)</span> гэж олдсон.</p>
<p>Эцэст нь хувьсагчдын хамаарал шугаман хэлбэртэй байгаа эсэхийг шугаман загварын оношлогооны диаграммын тусламжтай ажиглая. Үүний тулд&nbsp;Residuals vs Fitted диаграмм байгуулна.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-lm1-diagnoses-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lm1-diagnoses-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-lm1-diagnoses-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lm1-diagnoses-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;6: Шугаман загварын оношлогооны Residuals vs Fitted диаграмм
</figcaption>
</figure>
</div>
</div>
</div>
<p>Хэрэв хамаарал үнэхээр шугаман бол диаграмм дээрх улаан шугам бараг тэгш байх ёстой. Гэвч хугарсан мэт хэлбэр ажиглагдаж буй тул хамаарлыг шугаман биш гэж дүгнэнэ. Улмаар нэг л хугарал буй тул загварт квадрат эрэмбийн <span class="math inline">\(\text{нас}^2\)</span> тайлбарлах хувьсагч нэмнэ.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> seconds_bc <span class="sc">~</span> age <span class="sc">+</span> <span class="fu">I</span>(age<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> race)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Шинээр зохиосон хоёр дугаар эрэмбийн шугаман загварын хувьд Residuals vs Fitted диаграмм ахин байгуулъя.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit, <span class="at">which =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-lm2-diagnoses-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lm2-diagnoses-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-lm2-diagnoses-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lm2-diagnoses-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;7: Шугаман загварын оношлогооны Residuals vs Fitted диаграмм
</figcaption>
</figure>
</div>
</div>
</div>
<p>Одоо улаан шугам V, U эсвэл S гэх мэт тодорхой зүй тогтолгүй, зүгээр л тэгийн орчим хэлбэлзжээ. Иймд квадрат эрэмбийн загвар хангалттай. Гэхдээ дээр дурдсанчлан диаграммаас дүгнэлт гаргах нь өрөөсгөл тул үүнийг зохих шинжүүрээр шалгана. Ингээд загвар шугаман гэсэн тэг таамаглалыг Rainbow шинжүүр <span class="citation" data-cites="utts1982rainbow"><a href="#ref-utts1982rainbow" role="doc-biblioref">[10]</a></span> ашиглаж шалгана. Шинжүүрийг хэрэглэхдээ lmtest багц ашиглав.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">raintest</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Rainbow test

data:  fit
Rain = 1.1762, df1 = 46, df2 = 42, p-value = 0.2984</code></pre>
</div>
</div>
<p><span class="math inline">\(p\text{-утга}\)</span> 0.05 ач холбогдлын түвшингээс их гарсан нь шугаман загварын үлдэгдлийн хэлбэлзэл санамсаргүй гэсэн тэг таамаглалыг тус шинжүүр үл няцааж буйг илтгэнэ.</p>
<p>Мөн хоёр дугаар эрэмбийн шугаман загвар шинээр авч үзэж буй тул уг загварын үлдэгдлийн дисперс тогтмол эсэхийг ч шалгах хэрэгтэй.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>lmtest<span class="sc">::</span><span class="fu">bptest</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  fit
BP = 1.3871, df = 2, p-value = 0.4998</code></pre>
</div>
</div>
<p>Гарсан үр дүнг харвал үлдэгдлийн дисперс тогтмол гэсэн тэг таамаглал үл няцаагджээ.</p>
<p>Түүнчлэн шинэ загварын хувьд түүний үлдэгдэл хэвийн тархалттай гэсэн таамаглал үнэн эсэхийг бас л шалгах хэрэгтэй.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>fit <span class="sc">|&gt;</span> <span class="fu">residuals</span>() <span class="sc">|&gt;</span> <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  residuals(fit)
W = 0.98606, p-value = 0.4456</code></pre>
</div>
</div>
<p>Дээрх үр дүн хоёр дугаар эрэмбийн шугаман загварын үлдэгдэл хэвийн тархалттай гэсэн тэг таамаглалыг Шафиро-Уилкийн шинжүүр үл няцааж буйг илтгэнэ.</p>
<p>Ийнхүү урьдчилсан таамаглалууд үл зөрчигдөж буйг олж тогтоосноор <span class="math display">\[\text{seconds\_bc}=a+b\cdot\text{age}+c\cdot\text{age}^2\]</span> хоёр дугаар эрэмбийн шугаман загварыг найдвартай гэж үзэх үндэслэлтэй боллоо. Иймээс уг загварт тулгуурлан “Унадаг дугуйчдын амжилт наснаас хамаардаг уу?” гэсэн асуултад эцэслэн хариулна.</p>
<p>Унадаг дугуйчдын амжилт наснаас хамаардаг уу гэсэн асуулт нь дээрх хоёр дугаар эрэмбийн шугаман загвар статистик ач холбогдолтой юу гэсэн асуулттай эквивалент юм. Ийм асуултад F шинжүүрийн тусламжтай хариулт өгнө. F статистикийг загварын дүгнэгч статистикууд дундаас харж болно.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = seconds_bc ~ age + I(age^2), data = race)

Residuals:
       Min         1Q     Median         3Q        Max 
-2.052e-07 -6.670e-08  8.778e-09  6.460e-08  2.104e-07 

Coefficients:
              Estimate Std. Error    t value Pr(&gt;|t|)    
(Intercept)  5.882e-01  1.647e-07  3.572e+06   &lt;2e-16 ***
age          2.054e-08  9.951e-09  2.064e+00   0.0420 *  
I(age^2)    -2.831e-10  1.455e-10 -1.945e+00   0.0549 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.544e-08 on 88 degrees of freedom
Multiple R-squared:  0.05259,   Adjusted R-squared:  0.03106 
F-statistic: 2.442 on 2 and 88 DF,  p-value: 0.09283</code></pre>
</div>
</div>
<p>F шинжүүрийн <span class="math inline">\(p\text{-утга}\)</span> 0.05 ач холбогдлын түвшингээс их байгаа нь “унадаг дугуйчдын амжилт наснаас хамаардаг” гэсэн таамаглалыг статистик ач холбогдолтойгоор баталж чадахгүй байна гэсэн үг юм. Цаашилбал Adjusted R-squared 0.0310564 нь загвар (манай тохиолдолд нас) дугуйчдын амжилтын хэлбэлзлийн ердөө 3.1%-ийг л тайлбарлаж байна гэсэн үг. Үлдсэн 97% шахуу нь бэлтгэл сургуулилт, унадаг дугуйны чанар, туршлага гэх мэт наснаас өөр хүчин зүйлээс хамаарч байна.</p>
<p>Коэффициентүүдийн шинжилгээ буюу t шинжүүрийн үр дүнгээс насны дан болон квадрат эрэмбийн хувьсагчид нөлөөгүй болох нь харагдана. Иймд насыг тамирчдын амжилтыг тайлбарлахад ач холбогдолгүй гэж дүгнэнэ.</p>
<p>Ийнхүү тамирчдын амжилт наснаас хамаардаг гэсэн алтернатив таамаглал статистик ач холбогдолтойгоор батлагдахгүй байна.</p>
</section>
<section id="дисперсийн-шинжилгээ" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="дисперсийн-шинжилгээ"><span class="header-section-number">2.3</span> Дисперсийн шинжилгээ</h2>
<p>Тус тэмцээнд оролцсон сонирхогч ангиллын эрэгтэй тамирчдыг насаар нь 17-29, 30-39 болон 40-49 гэсэн гурван категороор ангилж уралдуулсан. Өдгөө ч уг ангилал өөрчлөгдөөгүй байна. Одоо нэмэлтээр тус насны ангиллын хувьд тамирчдын амжилтын статистик ач холбогдол бүхий ялгаа байна уу гэдгийг шинжилнэ.</p>
<p>Насны гурван категор дахь тамирчдын амжилт ижил гэсэн таамаглалыг дисперсийн шинжилгээний <span class="citation" data-cites="jamyansharav2023"><a href="#ref-jamyansharav2023" role="doc-biblioref">[11]</a></span> тусламжтай шалгаж болно. Үүний тулд эхлээд манай өгөгдөл дисперсийн шинжилгээний шаардлага хангах эсэхийг нягтална.</p>
<p>Насаар ангилсан гурван бүлэг бүрээрх тамирчдын амжилт буюу seconds хувьсагч хэвийн тархалттай. Насны бүлгүүд дэх тамирчдын амжилтын дисперс ижил.</p>
<p>Эхний таамаглалыг дараах байдлаар шалгана.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="st">"x"</span> <span class="ot">=</span> race, <span class="st">"subset"</span> <span class="ot">=</span> age <span class="sc">&lt;</span> <span class="dv">30</span>, <span class="at">select =</span> seconds, <span class="st">"drop"</span> <span class="ot">=</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  subset(x = race, subset = age &lt; 30, select = seconds, drop = TRUE)
W = 0.88401, p-value = 0.01442</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="st">"x"</span> <span class="ot">=</span> race, <span class="st">"subset"</span> <span class="ot">=</span> age <span class="sc">&gt;=</span><span class="dv">30</span> <span class="sc">&amp;</span> age <span class="sc">&lt;</span> <span class="dv">40</span>, <span class="at">select =</span> seconds, <span class="st">"drop"</span> <span class="ot">=</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  subset(x = race, subset = age &gt;= 30 &amp; age &lt; 40, select = seconds, drop = TRUE)
W = 0.97034, p-value = 0.3538</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="st">"x"</span> <span class="ot">=</span> race, <span class="st">"subset"</span> <span class="ot">=</span> age <span class="sc">&gt;=</span><span class="dv">40</span>, <span class="at">select =</span> seconds, <span class="st">"drop"</span> <span class="ot">=</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  subset(x = race, subset = age &gt;= 40, select = seconds, drop = TRUE)
W = 0.84687, p-value = 0.000809</code></pre>
</div>
</div>
<p>Гурван бүлэг тус бүртэй харгалзах шинжүүрийн <span class="math inline">\(p\text{-value}\)</span> харгалзан 0.01442, 0.3538 болон 0.000809 гэж гарсан. Эдгээрээс 17-29 болон 40-49 насны бүлэгт хамаатай <span class="math inline">\(p\text{-утга}\)</span> 0.05 ач холбогдлын түвшингээс байгаа нь тэдгээр бүлгийн хувьд тамирчдын амжилтыг илэрхийлэх <code>seconds</code> хувьсагч хэвийн бус тархалттай гэдгийг илтгэж буй явдал юм. Иймээс тэдгээр бүлэг дэх тархалт яагаад хэвийн биш байгааг нягтална. Ийм нөхцөл байдлын шалтгаан нь онцгой утга байх нь түгээмэл. Ингээд онцгой утга илрүүлэхийн тулд хайрцган диаграмм байгуулна.</p>
<p>Эхлээд 17-29 бүлгийг авч үзнэ.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="at">x =</span> race, <span class="at">subset =</span> age <span class="sc">&lt;</span> <span class="dv">30</span>, <span class="at">select =</span> seconds, <span class="at">drop =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">boxplot</span>() <span class="ot">-&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  bp</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Outliers:"</span>, bp<span class="sc">$</span>out)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Outliers: 5250</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-boxplot-17-29" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-17-29-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-boxplot-17-29-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-17-29-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;8: 17-29 насны тамирчдын амжилтын тархалт ба онцгой утга
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ингээд 5250 секунд гэсэн 1 ширхэг онцгой утга илрүүлэв. Энэ нь 1 цаг 27 минут 30 секунд гэсэн үг. Одоо тус утгыг оролцуулалгүйгээр таамаглал шалгана.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> race,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">subset =</span> age <span class="sc">&lt;</span> <span class="dv">30</span> <span class="sc">&amp;</span> seconds <span class="sc">&lt;</span> <span class="fu">min</span>(bp<span class="sc">$</span>out),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">select =</span> seconds,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">drop =</span> <span class="cn">TRUE</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  subset(x = race, subset = age &lt; 30 &amp; seconds &lt; min(bp$out), select = seconds, drop = TRUE)
W = 0.93497, p-value = 0.1731</code></pre>
</div>
</div>
<p><span class="math inline">\(p\text{-утга}\)</span> нь 0.05 ач холбогдлын түвшингээс багагүй болсоноор 17-29 насны тамирчдын амжилт хэвийн тархалттай биш гэж батлах үндэслэл үгүй боллоо. Тэгэхээр тархалтыг хэвийн бус болгож буй тус онцгой утгыг өгөгдлөөс зайлуулна.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>race <span class="ot">&lt;-</span> race[<span class="sc">!</span>{race<span class="sc">$</span>age <span class="sc">&lt;</span> <span class="dv">30</span> <span class="sc">&amp;</span> race<span class="sc">$</span>seconds <span class="sc">&gt;=</span> <span class="fu">min</span>(bp<span class="sc">$</span>out)},]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Одоо 40-49 бүлгийг авч үзнэ.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="at">x =</span> race, <span class="at">subset =</span> age <span class="sc">&gt;=</span> <span class="dv">40</span>, <span class="at">select =</span> seconds, <span class="at">drop =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">boxplot</span>() <span class="ot">-&gt;</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  bp</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Outliers:"</span>, bp<span class="sc">$</span>out)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Outliers: 4856 5477</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-boxplot-40-49" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-40-49-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-boxplot-40-49-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-40-49-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;9: 40-49 насны тамирчдын амжилтын тархалт ба онцгой утга
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ингээд 4856, 5477 секунд гэсэн 2 ширхэг онцгой утга илрүүлэв. Энэ нь 1 цаг 20 минут 56 секунд ба 1 цаг 31 минут 17 секунд гэсэн үг. Одоо эдгээр утгыг оролцуулалгүйгээр таамаглал шалгана.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> race,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">subset =</span> age <span class="sc">&gt;=</span> <span class="dv">40</span> <span class="sc">&amp;</span> seconds <span class="sc">&lt;</span> <span class="fu">min</span>(bp<span class="sc">$</span>out),</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">select =</span> seconds,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">drop =</span> <span class="cn">TRUE</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  subset(x = race, subset = age &gt;= 40 &amp; seconds &lt; min(bp$out), select = seconds, drop = TRUE)
W = 0.93098, p-value = 0.08178</code></pre>
</div>
</div>
<p><span class="math inline">\(p\text{-утга}\)</span> нь 0.05 ач холбогдлын түвшингээс багагүй болсоноор 40-49 насны тамирчдын амжилт хэвийн тархалттай биш гэж батлах үндэслэл үгүй боллоо. Тэгэхээр тархалтыг хэвийн бус болгож буй тэдгээр онцгой утгуудыг өгөгдлөөс зайлуулна.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>race <span class="ot">&lt;-</span> race[<span class="sc">!</span>{race<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">40</span> <span class="sc">&amp;</span> race<span class="sc">$</span>seconds <span class="sc">&gt;=</span> <span class="fu">min</span>(bp<span class="sc">$</span>out)},]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Одоо насны бүлгүүд дэх тамирчдын амжилтын дисперс ижил гэсэн таамаглалыг шалгана. Ийм таамаглалыг Бартлетийн шинжүүрээр <span class="citation" data-cites="bartlett1937properties"><a href="#ref-bartlett1937properties" role="doc-biblioref">[12]</a></span> шалгана. Үүний тулд насны бүлгийг илэрхийлэх хувьсагч хэрэгтэй.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>race<span class="sc">$</span>age_group <span class="ot">&lt;-</span> <span class="fu">cut</span>(</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> race<span class="sc">$</span>age,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">17</span>,<span class="dv">30</span>,<span class="dv">40</span>,<span class="dv">50</span>),</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"20"</span>, <span class="st">"30"</span>, <span class="st">"40"</span>),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">include.lowest =</span> <span class="cn">TRUE</span>, <span class="at">right =</span> <span class="cn">TRUE</span>, <span class="at">ordered_result =</span> <span class="cn">TRUE</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="fu">bartlett.test</span>(<span class="at">formula =</span> seconds <span class="sc">~</span> age_group, <span class="at">data =</span> race)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Bartlett test of homogeneity of variances

data:  seconds by age_group
Bartlett's K-squared = 5.1336, df = 2, p-value = 0.07678</code></pre>
</div>
</div>
<p>Дээрх үр дүн нь гурван бүлгийн дисперс тэнцүү гэдэг тэг таамаглалыг 0.05 ач холбогдлын түвшинд үл няцааж буйг илтгэнэ.</p>
<p>Ийнхүү дисперсийн шинжилгээний шаардлагыг манай өгөгдөл хангахгүй гэх статистик үндэслэл алга байгаа тул тус шинжилгээг хийж болно.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">formula =</span> seconds <span class="sc">~</span> age_group, <span class="at">data =</span> race)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df   Sum Sq Mean Sq F value Pr(&gt;F)
age_group    2   799930  399965   2.113  0.127
Residuals   85 16091830  189316               </code></pre>
</div>
</div>
<p><span class="math inline">\(p\text{-утга}=0.1272179&gt;0.05\)</span> байгаа нь насны гурван бүлэг ялгаатай гэдэг алтернатив таамаглал үл батлагдаж буйг илтгэнэ. Өөрөөр хэлбэл тамирчдын амжилт наснаас хамаардаг гэх статистик үндэслэл гарахгүй байна.</p>
<p>Ийнхүү янз бүрээр шинжилж үзсэний эцэст 17-50 насны унадаг дугуйн тамирчдын амжилт буюу гараанаас бариа хүртэл жийхдээ зарцуулах хугацаа наснаас хамаардаггүй гэх үндэслэл байна гэсэн дүгнэлтэд хүрлээ.</p>
<p>Эцэст нь тэмдэглэхэд нэг жил Монголын дугуйн холбоо (МДХ) унадаг дугуйчдыг гурван категорт ангилаад уралдуулж байж билээ. Тухайн үед МДХ-ны ЕНБД асан З.Наран хэлэхдээ олон улсад тамирчдыг насаар бус харин чансаагаар нь эрэмбэлэн ангилж уралдуулдаг жишгийн дагуу тийнхүү тамирчдыг насны бус ангилалаар хуваалаа гэсэн. Гэвч буцаад насаар ангилах болсон ба өдгөө ч насаар ангилах нь хэвээрээ л байна. Дээрх өгөгдлийн шинжилгээний үр дүнг харвал Наран ахын зөв байсан бололтой.</p>
</section>
</section>
<section id="нэмэлт-шинжилгээ" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Нэмэлт шинжилгээ</h1>
<section id="унадаг-дугуйчдын-жийлтийн-эрчим-хэвийн-тархалттай-эсэх" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="унадаг-дугуйчдын-жийлтийн-эрчим-хэвийн-тархалттай-эсэх"><span class="header-section-number">3.1</span> Унадаг дугуйчдын жийлтийн эрчим хэвийн тархалттай эсэх</h2>
<p>Цааш үргэлжлүүлэн seconds хувьсагч нормал тархалттай эсэхийг шалгав.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>race<span class="sc">$</span>seconds <span class="sc">|&gt;</span> <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  race$seconds
W = 0.96514, p-value = 0.01809</code></pre>
</div>
</div>
<p>Дээрх үр дүн бол хэвийн тархалттай гэсэн тэг таамаглал няцаагдаж буйг илтгэнэ. Ийнхүү няцаагдсан нь 5172 секунд буюу 1 цаг 26 минут 12 секунд гэсэн онцгой утгаас шалтгаалсан болохыг нэмэлт шинжилгээний явцад харагдана.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>race<span class="sc">$</span>seconds <span class="sc">|&gt;</span> <span class="fu">boxplot</span>() <span class="ot">-&gt;</span> bp</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>bp<span class="sc">$</span>out <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5172</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(<span class="at">x =</span> race, <span class="at">subset =</span> seconds <span class="sc">==</span> <span class="fu">min</span>(bp<span class="sc">$</span>out))<span class="sc">$</span>time <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "01:26:12"</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-boxplot-all" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-boxplot-all-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;10: Тамирчдын амжилтын тархалт ба онцгой утга
</figcaption>
</figure>
</div>
</div>
</div>
<p>Дээрх онцгой утгыг оролцуулахгүй бол хувьсагч хэвийн тархалттай гэсэн таамаглал 0.05 ач холбогдлын түвшинд үл няцаагдана. Энэ үр дүн дараах байдлаар гарсан.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> race,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">subset =</span> seconds <span class="sc">&lt;</span> <span class="fu">min</span>(bp<span class="sc">$</span>out),</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">select =</span> seconds,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">drop =</span> <span class="cn">TRUE</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro.test</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  subset(x = race, subset = seconds &lt; min(bp$out), select = seconds, drop = TRUE)
W = 0.97206, p-value = 0.05642</code></pre>
</div>
</div>
<p>Ингээд дээрх үр дүнд үндэслэн унадаг дугуйчдын жийлтийн эрчим хэвийн тархалттай гэж үзнэ.</p>
</section>
<section id="жийлтийн-эрчмийн-вариацын-цувааны-минимал-ба-максимал-элементүүдийн-корреляц" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="жийлтийн-эрчмийн-вариацын-цувааны-минимал-ба-максимал-элементүүдийн-корреляц"><span class="header-section-number">3.2</span> Жийлтийн эрчмийн вариацын цувааны минимал ба максимал элементүүдийн корреляц</h2>
<p>Унадаг дугуйчдын жийлтийн эрчмийг өөр хоорондоо хамааралгүй гэж тооцсон. Жийлтийн эрчим нь бэлтгэл сургуулилт, дадлага туршлага, унадаг дугуйн чанар зэргээс гадна хувь хүний бие физиологи хийгээд бусад онцлог ялгаа гэх мэт олон тусдаа хүчин зүйлийн нийлэмж тул ийм хамааралгүйн чанар үнэхээр хүчинтэй байж болно. Гэхдээ жийлтийн эрчмийг эрэмбэлэн жагсаах буюу вариацын цуваа байдлаар авч үзвэл хамааралтай болно.</p>
<p><span class="math inline">\(n\)</span> унадаг дугуйчин байг. Унадаг дугуйчдын жийлтийн эрчмийг илэрхийлэх санамсаргүй хувьсагчийг <span class="math inline">\(X\)</span> гэж тэмдэглэе. Тэгвэл тэдгээр дугуйчдын жийлтийн эрчмийг харгалзан <span class="math inline">\(X_1,X_2,\ldots,X_n\)</span> гэж тэмдэглэнэ. Дээр дурдсанчлан эдгээр хувьсагчид хамааралгүй бас хэвийн тархалттай. Харин эдгээрийг эрэмбэлэн жагсаахад үүсэх вариацын цувааны хувьд нөхцөл байдал өөр болно. Вариацын цувааны <span class="math inline">\(i\)</span> дүгээр элемент буюу <span class="math inline">\(i\)</span> дүгээр эрэмбийн статистикийг <span class="math inline">\(X_{(i)}\)</span> гэж тэмдэглэнэ. Ийнхүү <span class="math inline">\(X_1,X_2,\ldots,X_n\)</span> түүврийн элементүүдийг эрэмбэлсэнээр тэдгээр нь өөр хоорондоо хамааралтай болдог. Өөрөөр хэлбэл <span class="math inline">\(X_i\)</span> ба <span class="math inline">\(X_j\)</span> хоёр хамааралгүй ч эрэмбэлсэний дараах <span class="math inline">\(X_{(i)}\)</span> ба <span class="math inline">\(X_{(j)}\)</span> хоёр хамааралтай. Энэ бол тэмцээний тэргүүн байр эзэлсэн тамирчин ба баян ходоод болсон тамирчин хоёрын жийлтийн эрчим хамааралтай гэсэн үг юм. Нэгэнт эдгээр нь хамааралтай юм бол хамаарал нь хэр хүчтэй вэ гэсэн асуулт гарна. Ингээд <span class="math inline">\(X_{(1)}\)</span> ба <span class="math inline">\(X_{(n)}\)</span> буюу цувааны хамгийн эхний ба хамгийн сүүлийн элементүүдийн хоорондох корреляцийг олно. Уг корреляцийг илэрхийлэх томъёо төдийгүй томъёоны дагуух тооцоолол нарийн түвэгтэй тул тооцох бодох математикийн арга техник хэрэглэлээ. Эрэмбийн статистикийн тархалт гэх мэтчилэн шаардлагатай томъёонуудыг МУИС-ийн Статистик хөтөлбөрийн Математик статистик хичээлийн сурах бичиг <span class="citation" data-cites="jamyansharav2023"><a href="#ref-jamyansharav2023" role="doc-biblioref">[11]</a></span> дээрээс авсан. Тооцооллыг R програм дээр хийв.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>n_range <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">16</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">n =</span> n_range, <span class="at">rho =</span> <span class="cn">NA</span>)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>cov_order_stats <span class="ot">&lt;-</span> <span class="cf">function</span>(n, <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">sigma =</span> <span class="dv">1</span>) {</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># стандарт хэвийн тархалтын нягтын функц</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  phi <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">dnorm</span>(x)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># стандарт хэвийн тархалтын хуримтлагдах тархалтын функц</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  Phi <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">pnorm</span>(x)</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Z_(1)</span></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>  f_min <span class="ot">&lt;-</span> <span class="cf">function</span>(z){</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>    n <span class="sc">*</span> {<span class="dv">1</span> <span class="sc">-</span> <span class="fu">Phi</span>(z)} <span class="sc">**</span> {n<span class="dv">-1</span>} <span class="sc">*</span> <span class="fu">phi</span>(z)</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>  Ez1 <span class="ot">&lt;-</span> <span class="fu">integrate</span>(<span class="cf">function</span>(z) z <span class="sc">*</span> <span class="fu">f_min</span>(z), <span class="at">lower =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">upper =</span> <span class="cn">Inf</span>)<span class="sc">$</span>value</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>  Ez1_sq <span class="ot">&lt;-</span> <span class="fu">integrate</span>(<span class="cf">function</span>(z) z <span class="sc">**</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">f_min</span>(z), <span class="at">lower =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">upper =</span> <span class="cn">Inf</span>)<span class="sc">$</span>value</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>  Var_z1 <span class="ot">&lt;-</span> Ez1_sq <span class="sc">-</span> Ez1 <span class="sc">**</span> <span class="dv">2</span></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Z_(n)</span></span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>  Ez_n <span class="ot">&lt;-</span> <span class="sc">-</span> Ez1 <span class="co"># тархалт нь тэгш хэмтэй учраас</span></span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>  Var_zn <span class="ot">&lt;-</span> Var_z1</span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Z_(1) ба Z_(n) хоёрын хамтын нягт</span></span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>  joint_density <span class="ot">&lt;-</span> <span class="cf">function</span>(u, v) {</span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>    n <span class="sc">*</span> {n <span class="sc">-</span> <span class="dv">1</span>} <span class="sc">*</span> <span class="fu">phi</span>(u) <span class="sc">*</span> <span class="fu">phi</span>(v) <span class="sc">*</span> {<span class="fu">Phi</span>(v) <span class="sc">-</span> <span class="fu">Phi</span>(u)} <span class="sc">**</span> {n<span class="dv">-2</span>}</span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Z_(1) * Z_(n) үржвэрийн дундаж олоход шаардлагатай интегралчлах функц</span></span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a>  integrand_outer_scalar <span class="ot">&lt;-</span> <span class="cf">function</span>(u) {</span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a>    inner <span class="ot">&lt;-</span> <span class="cf">function</span>(v) {</span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a>      u <span class="sc">*</span> v <span class="sc">*</span> <span class="fu">joint_density</span>(u, v)</span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">integrate</span>(inner, <span class="at">lower =</span> u, <span class="at">upper =</span> <span class="cn">Inf</span>)<span class="sc">$</span>value</span>
<span id="cb61-33"><a href="#cb61-33" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb61-34"><a href="#cb61-34" aria-hidden="true" tabindex="-1"></a>  <span class="co"># integrate-д зориулж векторжуулах</span></span>
<span id="cb61-35"><a href="#cb61-35" aria-hidden="true" tabindex="-1"></a>  integrand_outer <span class="ot">&lt;-</span> <span class="fu">Vectorize</span>(integrand_outer_scalar)</span>
<span id="cb61-36"><a href="#cb61-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Z_(1) * Z_(n) үржвэрийн дундаж</span></span>
<span id="cb61-37"><a href="#cb61-37" aria-hidden="true" tabindex="-1"></a>  Ez1zn <span class="ot">&lt;-</span> <span class="fu">integrate</span>(integrand_outer, <span class="at">lower =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">upper =</span> <span class="cn">Inf</span>)<span class="sc">$</span>value</span>
<span id="cb61-38"><a href="#cb61-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-39"><a href="#cb61-39" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Z_(1) ба Z_(n) хоёрын ковариац</span></span>
<span id="cb61-40"><a href="#cb61-40" aria-hidden="true" tabindex="-1"></a>  Cov_z <span class="ot">&lt;-</span> Ez1zn <span class="sc">-</span> Ez1 <span class="sc">*</span> Ez_n</span>
<span id="cb61-41"><a href="#cb61-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-42"><a href="#cb61-42" aria-hidden="true" tabindex="-1"></a>  <span class="co"># масштабын хувиргалт</span></span>
<span id="cb61-43"><a href="#cb61-43" aria-hidden="true" tabindex="-1"></a>  Var1 <span class="ot">&lt;-</span> sigma <span class="sc">**</span> <span class="dv">2</span> <span class="sc">*</span> Var_z1</span>
<span id="cb61-44"><a href="#cb61-44" aria-hidden="true" tabindex="-1"></a>  VarN <span class="ot">&lt;-</span> sigma <span class="sc">**</span> <span class="dv">2</span> <span class="sc">*</span> Var_zn</span>
<span id="cb61-45"><a href="#cb61-45" aria-hidden="true" tabindex="-1"></a>  Cov12 <span class="ot">&lt;-</span> sigma <span class="sc">**</span> <span class="dv">2</span> <span class="sc">*</span> Cov_z</span>
<span id="cb61-46"><a href="#cb61-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-47"><a href="#cb61-47" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ковариацийн матриц</span></span>
<span id="cb61-48"><a href="#cb61-48" aria-hidden="true" tabindex="-1"></a>  Sigma <span class="ot">&lt;-</span> <span class="fu">matrix</span>(</span>
<span id="cb61-49"><a href="#cb61-49" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(</span>
<span id="cb61-50"><a href="#cb61-50" aria-hidden="true" tabindex="-1"></a>      Var1, Cov12,</span>
<span id="cb61-51"><a href="#cb61-51" aria-hidden="true" tabindex="-1"></a>      Cov12, VarN</span>
<span id="cb61-52"><a href="#cb61-52" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb61-53"><a href="#cb61-53" aria-hidden="true" tabindex="-1"></a>    <span class="at">nrow =</span> <span class="dv">2</span></span>
<span id="cb61-54"><a href="#cb61-54" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb61-55"><a href="#cb61-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-56"><a href="#cb61-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">list</span>(</span>
<span id="cb61-57"><a href="#cb61-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">Var_X1 =</span> Var1,</span>
<span id="cb61-58"><a href="#cb61-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">Var_Xn =</span> VarN,</span>
<span id="cb61-59"><a href="#cb61-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">Cov =</span> Cov12,</span>
<span id="cb61-60"><a href="#cb61-60" aria-hidden="true" tabindex="-1"></a>    <span class="at">Cov_matrix =</span> Sigma</span>
<span id="cb61-61"><a href="#cb61-61" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb61-62"><a href="#cb61-62" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb61-63"><a href="#cb61-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-64"><a href="#cb61-64" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(n_range)) {</span>
<span id="cb61-65"><a href="#cb61-65" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> n_range[i]</span>
<span id="cb61-66"><a href="#cb61-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-67"><a href="#cb61-67" aria-hidden="true" tabindex="-1"></a>  <span class="co"># эрэмбийн статистикуудын дисперс ба ковариац</span></span>
<span id="cb61-68"><a href="#cb61-68" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> <span class="fu">cov_order_stats</span>(n)</span>
<span id="cb61-69"><a href="#cb61-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-70"><a href="#cb61-70" aria-hidden="true" tabindex="-1"></a>  <span class="co"># корреляци: rho = Cov(X1, Xn) / sqrt(Var(X1) * Var(Xn))</span></span>
<span id="cb61-71"><a href="#cb61-71" aria-hidden="true" tabindex="-1"></a>  <span class="co"># симметр чанараар Var(X1) = Var(Xn)</span></span>
<span id="cb61-72"><a href="#cb61-72" aria-hidden="true" tabindex="-1"></a>  rho <span class="ot">&lt;-</span> v<span class="sc">$</span>Cov <span class="sc">/</span> v<span class="sc">$</span>Var_X1</span>
<span id="cb61-73"><a href="#cb61-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-74"><a href="#cb61-74" aria-hidden="true" tabindex="-1"></a>  results<span class="sc">$</span>rho[i] <span class="ot">&lt;-</span> rho</span>
<span id="cb61-75"><a href="#cb61-75" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb61-76"><a href="#cb61-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-77"><a href="#cb61-77" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>rho <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">|&gt;</span> <span class="fu">cat</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.467 0.295 0.213 0.166 0.135 0.114 0.099 0.087 0.078 0.07 0.064 0.059 0.054 0.05 0.047</code></pre>
</div>
</div>
<p>Ийнхүү <span class="math inline">\(n\geq2\)</span> хэмжээтэй түүврийн хувьд <span class="math inline">\(X_{(1)}\)</span> ба <span class="math inline">\(X_{(n)}\)</span> эрэмбийн статистикуудын корреляцийн коэффициентын утгыг оллоо. Эдгээрээс тухайлбал 0.099 нь <span class="math inline">\(n=8\)</span> унадаг дугуйчны жийлтийн эрчмээрээ хамгийн сайн ба муу хоёрын жийлтийн эрчмийн хамаарал (корреляцийн коэффициент) төдий хэмжээтэй гэдгийг илтгэнэ. Эдгээр корреляцийг цэг-шугаман диаграммаар дүрслэн харуулав.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">|&gt;</span> <span class="fu">plot</span>(</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"b"</span>,</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>),</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"n"</span>, <span class="at">ylab =</span> <span class="st">"correlation"</span>,</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"red"</span>)[{results<span class="sc">$</span>rho<span class="sc">&lt;</span><span class="fl">0.1</span>}<span class="sc">+</span><span class="dv">1</span>]</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fl">0.1</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">7</span>, <span class="at">y =</span> <span class="fu">min</span>(results<span class="sc">$</span>rho[results<span class="sc">$</span>rho <span class="sc">&gt;=</span> <span class="fl">0.1</span>]), <span class="at">labels =</span> <span class="st">"7"</span>, <span class="at">pos =</span> <span class="dv">3</span>)</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a><span class="fu">clip</span>(<span class="at">x1 =</span> <span class="dv">6</span>, <span class="at">x2 =</span> <span class="dv">8</span>, <span class="at">y1 =</span> <span class="dv">0</span>, <span class="at">y2 =</span> <span class="fu">min</span>(results<span class="sc">$</span>rho[results<span class="sc">$</span>rho <span class="sc">&gt;=</span> <span class="fl">0.1</span>]))</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">7</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-correlations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Bicycle-Race_files/figure-html/fig-correlations-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Зураг&nbsp;11: Хэвийн тархалттай эх олонлогоос авсан <span class="math inline">\(n\)</span> хэмжээтэй түүврийн нэг болон <span class="math inline">\(n\)</span> дүгээр эрэмбийн статистикуудын корреляц
</figcaption>
</figure>
</div>
</div>
</div>
<p>Цувааны минимал ба максимал элементүүдийн корреляц түүврийн хэмжээ өсөх тусам буурна. Гэхдээ хэзээ ч абсолют тэг утгад хүрэхгүй. Тэгэхээр түүврийн хэмжээ хэд болоход хоёр эрэмбийн статистикийг хамааралгүй гэж тооцож болох вэ гэсэн асуулт гарна. Энэ бол корреляцийн босго утгын тухай асуулт юм. Тухайлбал статистикт өргөн ашигладаг Коэны санал болгосон шатлал дахь “маш сул” хамааралтай харгалзах доод босго 0.1 байдаг. 0.1 утгыг сул хамаарлын доод босго гэж заасан өөр шатлалууд ч байдаг. Тэгэхээр корреляцийн утга 0.1 тооноос бага болох үед вариацын цувааны минимал ба максимал элементүүд статистик хамааралгүй гэж тооцно. Тэгвэл үүнд харгалзах түүврийн хэмжээ <span class="math inline">\(n=7\)</span> гэж олдоно. Энэ бол унадаг дугуйчдын тоо 8 байх үед цувааны толгойд яваа дугуйчны жийлтийн эрчим цувааны сүүлд яваа дугуйчинд нөлөөлөхгүй болно гэсэн үг юм. Нөгөө талд ийм үр дүн нь унадаг дугуйгаар хамтдаа яваа групп дугуйчдын тооны оновчтой максимал утгын тухай дүгнэлтэд хүргэнэ.</p>
</section>
</section>
<section id="дүгнэлт" class="level1 unnumbered">
<h1 class="unnumbered">Дүгнэлт</h1>
<ol type="1">
<li>Унадаг дугуйн спортын тамирчдын амжилт наснаас хамаардаг гэсэн алтернатив таамаглал статистик ач холбогдолтойгоор батлагдахгүй байна.</li>
<li>Эдүгээ хэрэгжиж буй насны ангилал болох 17-29, 30-39 болон 40-49 гурван бүлгийн хувьд тамирчдын амжилт ялгаатай гэх статистик үндэслэл алга байна.</li>
<li>Унадаг дугуйчдын жийлтийн эрчим хэвийн тархалттай.</li>
<li>Жийлтийн эрчмийн вариацын цувааны минимал ба максимал элементүүдийн корреляц нь түүврийн хэмжээ <span class="math inline">\(n&gt;7\)</span> үед маш сул хамаарлын босго 0.1 утгаас бага болно.</li>
</ol>
</section>
<section id="ашигласан-материал" class="level1 unnumbered">
<h1 class="unnumbered">Ашигласан материал</h1>
<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-mcf_facebook" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">Mongolian Cycling Federation, <span>“Mongolian cycling federation facebook page.”</span> 2014. Available: <a href="https://www.facebook.com/people/Mongolian-Cycling-Federation/100064467231837/">https://www.facebook.com/people/Mongolian-Cycling-Federation/100064467231837/</a></div>
</div>
<div id="ref-magadlal_web" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">Г.Махгал, <span>“Магадлал статистик веб сайт.”</span> 2016. Available: <a href="https://www.magadlal.com">https://www.magadlal.com</a></div>
</div>
<div id="ref-R" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">R Core Team, <em>R: A language and environment for statistical computing</em>. Vienna, Austria: R Foundation for Statistical Computing, 2025. Available: <a href="https://www.R-project.org/">https://www.R-project.org/</a></div>
</div>
<div id="ref-james2021introduction" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">G. James, D. Witten, T. Hastie, and R. Tibshirani, <em>An introduction to statistical learning: With applications in r</em>. Springer, 2021. Available: <a href="https://www.statlearning.com/">https://www.statlearning.com/</a></div>
</div>
<div id="ref-breusch1979simple" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline">T. S. Breusch and A. R. Pagan, <span>“A simple test for heteroscedasticity and random coefficient variation,”</span> <em>Econometrica</em>, vol. 47, no. 5, pp. 1287–1294, 1979, Available: <a href="https://www.jstor.org/stable/1911995">https://www.jstor.org/stable/1911995</a></div>
</div>
<div id="ref-zeileis2002diagnostic" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div><div class="csl-right-inline">A. Zeileis and T. Hothorn, <span>“Diagnostic checking in regression relationships,”</span> <em>R News</em>, vol. 2, no. 3, pp. 7–10, 2002, Available: <a href="https://CRAN.R-project.org/doc/Rnews/">https://CRAN.R-project.org/doc/Rnews/</a></div>
</div>
<div id="ref-shapiro1965analysis" class="csl-entry" role="listitem">
<div class="csl-left-margin">[7] </div><div class="csl-right-inline">S. S. Shapiro and M. B. Wilk, <span>“An analysis of variance test for normality (complete samples),”</span> <em>Biometrika</em>, vol. 52, no. 3/4, pp. 591–611, 1965, Available: <a href="https://www.jstor.org/stable/2333709">https://www.jstor.org/stable/2333709</a></div>
</div>
<div id="ref-boxcox1964" class="csl-entry" role="listitem">
<div class="csl-left-margin">[8] </div><div class="csl-right-inline">G. E. P. Box and D. R. Cox, <span>“An analysis of transformations,”</span> <em>Journal of the Royal Statistical Society. Series B (Methodological)</em>, vol. 26, no. 2, pp. 211–252, 1964, Available: <a href="https://www.jstor.org/stable/2984418">https://www.jstor.org/stable/2984418</a></div>
</div>
<div id="ref-venables2002modern" class="csl-entry" role="listitem">
<div class="csl-left-margin">[9] </div><div class="csl-right-inline">W. N. Venables and B. D. Ripley, <em>Modern applied statistics with s</em>, Fourth. New York: Springer, 2002. Available: <a href="https://www.stats.ox.ac.uk/pub/MASS4/">https://www.stats.ox.ac.uk/pub/MASS4/</a></div>
</div>
<div id="ref-utts1982rainbow" class="csl-entry" role="listitem">
<div class="csl-left-margin">[10] </div><div class="csl-right-inline">J. M. Utts, <span>“The rainbow test for lack of fit in regression,”</span> <em>Communications in Statistics - Theory and Methods</em>, vol. 11, no. 24, pp. 2801–2815, 1982, doi: <a href="https://doi.org/10.1080/03610928208828423">10.1080/03610928208828423</a>.</div>
</div>
<div id="ref-jamyansharav2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">[11] </div><div class="csl-right-inline">Б.Жамъяншарав, <em>Математик статистик</em>, Анхны хэвлэл. Улаанбаатар: МУИС, 2023.</div>
</div>
<div id="ref-bartlett1937properties" class="csl-entry" role="listitem">
<div class="csl-left-margin">[12] </div><div class="csl-right-inline">M. S. Bartlett, <span>“Properties of sufficiency and statistical tests,”</span> <em>Proceedings of the Royal Society of London. Series A-Mathematical and Physical Sciences</em>, vol. 160, no. 901, pp. 268–282, 1937, Available: <a href="https://doi.org/10.1098/rspa.1937.0109">https://doi.org/10.1098/rspa.1937.0109</a></div>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>